language: android
sudo: required
jdk: oraclejdk8
env:
  matrix:
    - ANDROID_TARGET=android-22 ANDROID_ABI=armeabi-v7a
  global:
    - ADB_INSTALL_TIMEOUT=10

before_install:
  - rm -rf $ANDROID_HOME/tools
  - wget https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip
  - unzip -o sdk-tools-linux-3859397.zip -d $ANDROID_HOME/
  - chmod +x gradlew
  - cp -r config/ci/licenses $ANDROID_HOME/
  - $ANDROID_HOME/tools/bin/sdkmanager "tools" --channel=3
  - $ANDROID_HOME/tools/bin/sdkmanager "build-tools;26.0.1" --channel=3
  - $ANDROID_HOME/tools/bin/sdkmanager "emulator" --channel=3
  - $ANDROID_HOME/tools/bin/sdkmanager "platform-tools" --channel=3
  - $ANDROID_HOME/tools/bin/sdkmanager "platforms;android-25" --channel=3
  - $ANDROID_HOME/tools/bin/sdkmanager "sources;$ANDROID_TARGET" --channel=3
  - $ANDROID_HOME/tools/bin/sdkmanager "system-images;$ANDROID_TARGET;default;$ANDROID_ABI" --channel=3

before_script:
  - echo no | android create avd --force --name test --target $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &

script:
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &
  - ./gradlew check connectedCheck -PdisablePreDex --stacktrace
