language: android
sudo: false
jdk: oraclejdk8
env:
  - ANDROID_TARGET=android-22 ANDROID_ABI=armeabi-v7a
android:
  components:
    - tools
    - android-22
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-google-google_play_services
    - extra-android-support
    - sys-img-$ANDROID_ABI-$ANDROID_TARGET
before_install:
  - chmod +x gradlew
  - cp -r config/ci/licenses $ANDROID_HOME/
  
before_script:
  - echo no | android create avd --force --name test --target $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &

script:
  - ./gradlew check -PdisablePreDex --stacktrace
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &
  - ./gradlew :mobile:connectedCheck -PdisablePreDex --stacktrace

